apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
   {{- include "ui.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: react-ui
  type: LoadBalancer
